### ISSUE TITLE
ReferenceError: bindRemoteObject is not defined

### ISSUE THREAD

**Issue by kernelp4nic** [binaryage/cljs-devtools#14]
Devtools is broken in the latest version of Chrome Canary (`Version 51.0.2689.0 canary (64-bit)`)

![2016-03-24_10-41-32](https://cloud.githubusercontent.com/assets/519481/14019257/9d036ca0-f1b0-11e5-9f53-95573b35749f.png)

Works fine in Chrome (`Version 49.0.2623.87 (64-bit)`). Same app btw.

**Comment by darwin** [comment]
Confirmed. Must broke in pretty recent version, a few canaries back. Will look into that over the weekend.

**Comment by darwin** [comment]
It seems there is nothing I can do about it right now. We have to wait for upstream fixes in Canary builds.

**Comment by darwin** [comment]
I have raised the issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=599884

**Comment by darwin** [comment]
Fixed in 51.0.2702.0 canary (64-bit).

**Comment by kernelp4nic** [comment]
Broken again!

```
Installing CLJS DevTools v0.6.1 and enabling features :custom-formatters :sanity-hints
core.cljs:24Feature :custom-formatters cannot be installed. Unsupported browser Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1.

Feature 'custom-formatters' cannot be installed. Unsupported browser Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1.
```

Canary Version:
`Version 52.0.2722.0 canary (64-bit)`

Devtools Version:
`[binaryage/devtools "0.6.1"]`

**Comment by darwin** [comment]
You are probably using some extension or DevTools feature which is reporting iPhone in browser's user-agent.

If you really need to do that, you can monkey-patch [this function](https://github.com/binaryage/cljs-devtools/blob/0ec51b1ef72d12afc1292ee8c00a5be8e6f819ba/src/devtools/custom_formatters.cljs#L13-L14) before calling `devtools.core/install!`.

**Comment by kernelp4nic** [comment]
Oh! yes I'm using "Toggle device toolbar", I'm going to patch the fn.
Thanks!

**Comment by qthompson** [comment]
I might be going crazy, but I’m still getting this error when expanding logged vectors only (I think...):

`Custom Formatter Failed: ReferenceError: bindRemoteObject is not defined`

Canary Version (mac):
`Version 52.0.2726.0 canary (64-bit)`

Devtools Version:
`[binaryage/devtools "0.6.1"]`

Can you think of any reason I’d still be running into this? Does expanding vectors via the disclosure indicator work for anybody else on later releases of Chrome Canary?

**Comment by darwin** [comment]
I can confirm that the bug was fixed around ~51.0.2722.0 and is still fixed in 52.0.2726.0. I have just tested it here with the latest canary.

**Comment by darwin** [comment]
Try canary with absolutely clean user profile: 

```
/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary \
--no-first-run \
--user-data-dir=.test-dirac-chrome-profile
```

**Comment by qthompson** [comment]
I’ve performed a little more testing in a new profile (using the above), and I’ve tried to keep the test quite minimal. When running into this issue in my actual application code, the values being logged are larger/more complex/more nested/etc. 

Running this:
```clojure
(.log js/console {:value "b"
                  :map {:some-key "some-val"}
                  :vec [{:1 "1-val"
                         :2 "2-val"
                         :3 {:3-val-k "3-val"}
                         ;; :4 (range 0 20)
                         }]})
```
Results in me being able to expand the `vec` disclosure indicator, but not the top-level one.
![image](https://cloud.githubusercontent.com/assets/15455746/15078513/76cd7202-13ab-11e6-9557-19b3990d42db.png)


Running this:
```clojure
(.log js/console {:value "b"
                  :map {:some-key "some-val"}
                  :vec [{:1 "1-val"
                         :2 "2-val"
                         :3 {:3-val-k "3-val"}
                         :4 (range 0 20)}]})
```
Results in me not being able to expand any of the disclosure indicators.
![image](https://cloud.githubusercontent.com/assets/15455746/15078551/a1952bc4-13ab-11e6-9e0b-36c7bf62d693.png)

I know it’s a pain, but could you confirm whether those code snippets behave correctly for you?

I’m definitely running Chrome Canary `Version 52.0.2726.0 canary (64-bit)`, with devtools `[binaryage/devtools "0.6.1"]`

![image](https://cloud.githubusercontent.com/assets/15455746/15078659/270c91ca-13ac-11e6-896d-8f48f0410126.png)

![image](https://cloud.githubusercontent.com/assets/15455746/15078687/49f3bcb8-13ac-11e6-9b63-750971ecf468.png)

**Comment by darwin** [comment]
just tested it under clean canary here on my Mac and it works just fine:
https://dl.dropboxusercontent.com/u/559047/problematic-cf-issue-14.png

https://github.com/binaryage/cljs-devtools-sample/commit/b7d997894df1ea8c082845a33ec66a80a8320e63

**Comment by darwin** [comment]
Also I have tested the version with uncommented `(range o 20)` and it works as expected for me.

It is really strange what you are experiencing. Like your DevTools talking to some old code inside Chrome for some reason.

**Comment by qthompson** [comment]
Thanks for taking the time to test that for me.

I’ll see if I can figure out what is going on with my Chrome install then!

**Comment by qthompson** [comment]
To keep this issue updated:

I didn’t manage to get it working correctly on Chrome Canary (complete reinstalls, new profiles, toggling custom formatters etc), however I switched to Chrome Stable (`Version 50.0.2661.102 (64-bit)`) and it’s working as expected for now. Not sure what that means as I receive future Chrome Stable update, but hopefully I am safe.

Thanks again for your help.

**Comment by darwin** [comment]
I have just opened a new issue upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=618745

**Comment by vikeri** [comment]
Seeing this in 51.0.2704.106 (64-bit) (macOS)

**Comment by darwin** [comment]
Please reopen if you encounter it again in recent Chrome versions.
